version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: adminpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql
  backend:
    build: ./backend-nest/
    container_name: nest_app
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend-nest/.env
    ports:
      - "3001:3001"
    volumes:
      - ./backend-nest:/app
      - /app/node_modules
    command: ["yarn", "start:dev"]
  frontend:
    build: ./frontend-next/
    container_name: next_app
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-next:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:3001
    command: ["npm", "run", "dev"]

volumes:
  pgdata: